### ISSUE TITLE
pricing in widget still using LIKE standard legacy model

### ISSUE THREAD

**Issue by ckxpress** [likecoin/likecoin-wordpress#258]
should be USD2

![Screenshot 2023-10-18 at 8 08 26 PM](https://github.com/likecoin/likecoin-wordpress/assets/7088918/d3cb3f9a-0b42-4762-8ebc-f25fad025c53)

**Comment by williamchong** [comment]
Fix in https://github.com/likecoin/likecoin-button/pull/497
