### ISSUE TITLE
LikeCoin Button Disappeared in ver 1.2.3

### ISSUE THREAD

**Issue by john970473** [likecoin/likecoin-wordpress#58]
I think there has some bug for this version.

**Comment by williamchong007** [comment]
Hmm we are always running the latest version in our own wordpress site before releasing to public, and it seems normal on our sites.
Can you describe what kind of `disappear` are you experiencing, and how can we reproduce it?

FYI [cloudflare had a huge downtime ~1 hour ago](https://www.cloudflarestatus.com/incidents/tx4pgxs6zxdr), so if you are seeing 502 errors that might be related to the incident

**Comment by john970473** [comment]
Not 502 error.
Anyone who update to 1.2.3 cannot see their button in the post or with shortcode.
I have the same situation even if I use the program's dockerfile.

**Comment by williamchong007** [comment]
@john970473 Can you try apply this patch and see if that was the problem?
https://github.com/likecoin/likecoin-wordpress/pull/59
Thanks

**Comment by john970473** [comment]
That's great!
I add   "$option = get_option( LC_OPTION_NAME );" and the button display.

**Comment by williamchong007** [comment]
Sorry for the trouble, and thanks for reporting
I will merge the PR make a new release soon

**Comment by john970473** [comment]
Thanks for a quick modification!
