### ISSUE TITLE
Confirming the liker ID result on blank page

### ISSUE THREAD

**Issue by Getron** [likecoin/likecoin-wordpress#77]
Hi

Just want to implement Likecoin into my page, all is gone ok, until the "Confirm" green button, if i click it, it just shows a blank page, and my ID is not tied to my user.

This happend to all users, not just admins.

Can you please look at this and fix it? I have 5.5.1 WP. I try to deactivate couple of plugins i thinked maybe can make a problem, but, nothing, the same blank page.

Liker ID is founded, just it wont confirm it, after clicking "Confirm" button - shows a blank page, and nothing happend.

it just open this location:
.../wp-admin/admin-post.php
result: blank page, and nothing saved.

Thanks

**Comment by williamchong** [comment]
Thanks for reporting.
This issue should be fixed in 2.0.1 release, please check if it works.

**Comment by Getron** [comment]
@williamchong Yes, not is working ok.

But, have a question, about the Mobile App, why is allmost all in Chines or Japan language? Can you please tell me, where i can go and tell this devs to make an english version of it, because, it 50-50% now in english and chinese (or japanese). The site is too just in chinese lang, Please to make it for other people readable, english, german, and so on.

Many thanks for fixint the problem.

**Comment by williamchong** [comment]
The app repo is in https://github.com/likecoin/likecoin-app
Please open an issue there if you find missing translations, thanks.
