### ISSUE TITLE
Publishing settings checkbox is always unchecked

### ISSUE THREAD

**Issue by jackysee** [likecoin/likecoin-wordpress#79]
![image](https://user-images.githubusercontent.com/30516/92345346-9ece5000-f0fb-11ea-8ab8-4ab905d6e11b.png)

The checkboxes in setting is always unchecked, even after clicked and save.

**Comment by williamchong** [comment]
Thanks for reporting. Can you confirm that both ticks does not save, or is it only the auto publish on won't save?

**Comment by jackysee** [comment]
The ticks is saved. It can auto publish.

**Comment by williamchong** [comment]
Does the "save draft" checkbox have similar issue too?

**Comment by jackysee** [comment]
save draft checkbox is ok. It can show the checked state.

**Comment by williamchong** [comment]
This issue will be fixed in 2.0.2 release
I am preparing the release now, please check if the fix works after the release is published on WordPress
Again thanks for reporting
