### ISSUE TITLE
Add an original link at bottom/top when publish to matters

### ISSUE THREAD

**Issue by jackysee** [likecoin/likecoin-wordpress#81]
When publish to matters, it would be nice to have an original link at the bottom of the article. e.g. `(原文刊於<a href="xxx">XXX</a>)`. The link would be the permalink of the article and the text would be the name of blog.

**Comment by williamchong** [comment]
Good idea, will implement this when I have time.
A PR would also be welcomed.

**Comment by williamchong** [comment]
Added in https://github.com/likecoin/likecoin-wordpress/pull/83
